name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
  

    steps:
      - uses: subosito/flutter-action@v2
      - uses: actions/checkout@v3
      - name: "Dependencies"
        run: flutter pub get
      - name: "Build"
        run: flutter build web
      - name: "zip"
        run: zip -r Latest.zip build/web/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: Latest.zip
