name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  WebAndLinux:
    name: "Ubuntu builds - web and linux"
    runs-on: "ubuntu-latest"
    steps:
      - uses: subosito/flutter-action@v2
      - uses: actions/checkout@v3
      - name: "Dependencies"
        run: flutter pub get
      - name: "Build"
        run: flutter build web --release --web-renderer canvaskit
      - name: "zip"
        run: zip -r LatestWeb.zip build/web/

      - uses: "marvinpinto/action-automatic-releases@latest"
        id: 'auto-releases'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Versions"
          files: LatestWeb.zip

      - name: "print url"
        run: echo ${{ steps.auto-releases.outputs.upload_url }}
  Windows:
    needs: WebAndLinux
    name: "Windows build"
    runs-on: "windows-latest"
    steps:
      - uses: subosito/flutter-action@v2
      - uses: actions/checkout@v3
      - name: "GH Stuff"
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "Dependencies"
        run: flutter pub get
      - name: "Windows build"
        run: flutter build windows
      - name: "print stuff"
        run: echo "${{ steps.latest_release_info.outputs.id }}"
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/windows/x64/runner/release/music_lessons_attendance.exe"
          tags: false
          draft: false
          verbose: true

      
